import type {
  AuditEvent,
  Company,
  IndustryEdge,
  IndustryNode,
  ResearchTask,
  User,
} from "../src/types.js";

export const users: User[] = [
  { id: "u-investor", name: "陈晨", role: "investor", projectIds: ["p-orbit"] },
  {
    id: "u-partner",
    name: "吕总",
    role: "partner",
    projectIds: ["p-orbit", "p-launch"],
  },
  {
    id: "u-admin",
    name: "知识管理员",
    role: "knowledge_admin",
    projectIds: [],
  },
  { id: "u-system", name: "系统管理员", role: "system_admin", projectIds: [] },
];

export const industryNodes: IndustryNode[] = [
  {
    id: "space",
    name: "商业航天",
    parentId: null,
    level: 0,
    source: "【余香斋】【商业航天】图谱",
  },
  {
    id: "foundation",
    name: "基础产业",
    parentId: "space",
    level: 1,
    source: "【余香斋】【商业航天】图谱",
  },
  {
    id: "satellite",
    name: "卫星研发及制造",
    parentId: "space",
    level: 1,
    source: "【余香斋】【商业航天】图谱",
  },
  {
    id: "launch",
    name: "运载火箭制造与发射",
    parentId: "space",
    level: 1,
    source: "【余香斋】【商业航天】图谱",
  },
  {
    id: "ground",
    name: "地面设备",
    parentId: "space",
    level: 1,
    source: "【余香斋】【商业航天】图谱",
  },
  {
    id: "service",
    name: "运营服务与应用",
    parentId: "space",
    level: 1,
    source: "【余香斋】【商业航天】图谱",
  },
  {
    id: "materials",
    name: "基础材料",
    parentId: "foundation",
    level: 2,
    source: "【余香斋】【商业航天】图谱",
  },
  {
    id: "components",
    name: "电子元器件",
    parentId: "foundation",
    level: 2,
    source: "【余香斋】【商业航天】图谱",
  },
  {
    id: "sat-platform",
    name: "卫星平台系统",
    parentId: "satellite",
    level: 2,
    source: "【余香斋】【商业航天】图谱",
  },
  {
    id: "sat-payload",
    name: "有效载荷系统",
    parentId: "satellite",
    level: 2,
    source: "【余香斋】【商业航天】图谱",
  },
  {
    id: "rocket-engine",
    name: "火箭推进系统",
    parentId: "launch",
    level: 2,
    source: "【余香斋】【商业航天】图谱",
  },
  {
    id: "rocket-structure",
    name: "结构系统（箭体结构）",
    parentId: "launch",
    level: 2,
    source: "【余香斋】【商业航天】图谱",
  },
  {
    id: "ground-station",
    name: "地面站",
    parentId: "ground",
    level: 2,
    source: "【余香斋】【商业航天】图谱",
  },
  {
    id: "terminal",
    name: "终端设备",
    parentId: "ground",
    level: 2,
    source: "【余香斋】【商业航天】图谱",
  },
  {
    id: "remote-sensing",
    name: "卫星遥感服务",
    parentId: "service",
    level: 2,
    source: "【余香斋】【商业航天】图谱",
  },
  {
    id: "navigation",
    name: "卫星导航服务",
    parentId: "service",
    level: 2,
    source: "【余香斋】【商业航天】图谱",
  },
  {
    id: "sat-comms",
    name: "卫星通信服务",
    parentId: "service",
    level: 2,
    source: "【余香斋】【商业航天】图谱",
  },
  {
    id: "sat-internet",
    name: "卫星互联网",
    parentId: "service",
    level: 2,
    source: "【余香斋】【商业航天】图谱",
  },
];

export const industryEdges: IndustryEdge[] = [
  {
    id: "ie-1",
    fromNodeId: "materials",
    toNodeId: "sat-platform",
    relation: "upstream_of",
    label: "提供结构与功能材料",
    source: "Demo 产业链规则",
  },
  {
    id: "ie-2",
    fromNodeId: "components",
    toNodeId: "sat-platform",
    relation: "upstream_of",
    label: "提供星载电子元器件",
    source: "Demo 产业链规则",
  },
  {
    id: "ie-3",
    fromNodeId: "sat-payload",
    toNodeId: "sat-platform",
    relation: "supports",
    label: "集成通信与遥感载荷",
    source: "Demo 产业链规则",
  },
  {
    id: "ie-4",
    fromNodeId: "sat-platform",
    toNodeId: "ground-station",
    relation: "serves",
    label: "在轨卫星连接地面测运控",
    source: "Demo 产业链规则",
  },
  {
    id: "ie-5",
    fromNodeId: "sat-platform",
    toNodeId: "terminal",
    relation: "serves",
    label: "面向用户终端提供接入",
    source: "Demo 产业链规则",
  },
  {
    id: "ie-6",
    fromNodeId: "sat-platform",
    toNodeId: "sat-internet",
    relation: "serves",
    label: "构成低轨通信网络基础设施",
    source: "Demo 产业链规则",
  },
  {
    id: "ie-7",
    fromNodeId: "ground-station",
    toNodeId: "sat-internet",
    relation: "supports",
    label: "提供测控与网络运营支撑",
    source: "Demo 产业链规则",
  },
  {
    id: "ie-8",
    fromNodeId: "terminal",
    toNodeId: "sat-internet",
    relation: "supports",
    label: "连接行业与个人用户",
    source: "Demo 产业链规则",
  },
];

export const companies: Company[] = [
  {
    id: "c-galaxy",
    standardName: "银河航天（北京）科技有限公司",
    aliases: ["银河航天", "GalaxySpace"],
    englishName: "GalaxySpace",
    description: "商业航天企业，聚焦低轨宽带通信卫星及卫星互联网相关能力。",
    cognitionStatus: "已人工确认",
    attentionStatus: "持续跟踪",
    updatedAt: "2026-08-06T08:30:00.000Z",
    positions: [
      {
        nodeId: "sat-platform",
        positionType: "primary",
        status: "confirmed",
        confidence: 0.96,
        source: "internal_evidence",
        sourceDate: "2026-07-28",
      },
      {
        nodeId: "sat-internet",
        positionType: "secondary",
        status: "candidate",
        confidence: 0.82,
        source: "source_map",
        sourceDate: "2025-12-03",
      },
    ],
    evidence: [
      {
        id: "e-g1",
        documentId: "d-g1",
        fileName: "银河航天项目初筛记录.docx",
        excerpt: "公司以低轨宽带通信卫星研制为核心，并参与卫星互联网技术验证。",
        page: 3,
        sourceDate: "2026-07-18",
        visibility: "organization",
      },
      {
        id: "e-g2",
        documentId: "d-g2",
        fileName: "银河航天访谈纪要.docx",
        excerpt: "本轮沟通重点核实批产能力、单星成本和在轨交付节奏。",
        page: 2,
        sourceDate: "2026-07-25",
        visibility: "project",
        projectId: "p-orbit",
      },
      {
        id: "e-g3",
        documentId: "d-g3",
        fileName: "陈晨个人判断.md",
        excerpt: "技术路径较清晰，但商业订单兑现节奏仍需观察。",
        sourceDate: "2026-07-27",
        visibility: "private",
        ownerId: "u-investor",
      },
    ],
    claims: [
      {
        id: "cl-g1",
        category: "主营产品",
        text: "主营低轨宽带通信卫星及相关系统。",
        type: "verified_fact",
        status: "confirmed",
        confidence: 0.96,
        version: 2,
        evidenceIds: ["e-g1"],
        visibility: "organization",
      },
      {
        id: "cl-g2",
        category: "产业位置",
        text: "主要位于卫星平台系统环节，并与卫星互联网服务相关。",
        type: "verified_fact",
        status: "confirmed",
        confidence: 0.91,
        version: 2,
        evidenceIds: ["e-g1", "e-g2"],
        visibility: "organization",
      },
      {
        id: "cl-g3",
        category: "商业进展",
        text: "企业材料称已具备规模化批产条件。",
        type: "company_statement",
        status: "disputed",
        confidence: 0.72,
        version: 1,
        evidenceIds: ["e-g2"],
        visibility: "project",
        projectId: "p-orbit",
      },
      {
        id: "cl-g4",
        category: "投资判断",
        text: "商业订单兑现节奏仍需观察。",
        type: "user_view",
        status: "candidate",
        confidence: 0.78,
        version: 1,
        evidenceIds: ["e-g3"],
        visibility: "private",
        ownerId: "u-investor",
      },
    ],
  },
  {
    id: "c-landspace",
    standardName: "蓝箭航天空间科技股份有限公司",
    aliases: ["蓝箭航天", "LandSpace"],
    englishName: "LandSpace",
    description: "商业运载火箭企业，覆盖液体火箭发动机与运载火箭系统。",
    cognitionStatus: "已匹配产业链",
    attentionStatus: "个人关注",
    updatedAt: "2026-08-05T10:20:00.000Z",
    positions: [
      {
        nodeId: "rocket-engine",
        positionType: "primary",
        status: "confirmed",
        confidence: 0.95,
        source: "source_map",
        sourceDate: "2025-12-03",
      },
      {
        nodeId: "rocket-structure",
        positionType: "secondary",
        status: "candidate",
        confidence: 0.76,
        source: "ai_recommendation",
        sourceDate: "2026-08-05",
      },
    ],
    evidence: [
      {
        id: "e-l1",
        documentId: "d-l1",
        fileName: "商业航天行业研究.pdf",
        excerpt: "液氧甲烷发动机是新一代商业运载火箭的重要技术路线之一。",
        page: 18,
        sourceDate: "2026-06-30",
        visibility: "organization",
      },
    ],
    claims: [
      {
        id: "cl-l1",
        category: "技术路线",
        text: "核心技术路线涉及液氧甲烷动力。",
        type: "verified_fact",
        status: "confirmed",
        confidence: 0.94,
        version: 1,
        evidenceIds: ["e-l1"],
        visibility: "organization",
      },
    ],
  },
  {
    id: "c-charming",
    standardName: "长光卫星技术股份有限公司",
    aliases: ["长光卫星"],
    description: "卫星研制与遥感信息服务企业。",
    cognitionStatus: "已自动补全",
    attentionStatus: "机构未关注",
    updatedAt: "2026-08-04T02:00:00.000Z",
    positions: [
      {
        nodeId: "satellite",
        positionType: "primary",
        status: "candidate",
        confidence: 0.87,
        source: "source_map",
        sourceDate: "2025-12-03",
      },
      {
        nodeId: "remote-sensing",
        positionType: "secondary",
        status: "candidate",
        confidence: 0.88,
        source: "source_map",
        sourceDate: "2025-12-03",
      },
    ],
    evidence: [
      {
        id: "e-c1",
        documentId: "d-map",
        fileName: "【余香斋】【商业航天】图谱.pdf",
        excerpt: "图谱将长光卫星列入卫星研发制造与遥感服务相关环节。",
        page: 1,
        sourceDate: "2025-12-03",
        visibility: "organization",
      },
    ],
    claims: [
      {
        id: "cl-c1",
        category: "图谱位置",
        text: "来源图谱显示公司横跨卫星制造与遥感服务环节，待进一步核验。",
        type: "external_view",
        status: "candidate",
        confidence: 0.83,
        version: 1,
        evidenceIds: ["e-c1"],
        visibility: "organization",
      },
    ],
  },
  {
    id: "c-aero-electronics",
    standardName: "航天电子元器件示范公司",
    aliases: ["航天电子示范"],
    description:
      "Demo 模拟企业：为低轨通信卫星提供星载计算、微波器件和电源组件。",
    cognitionStatus: "Demo 模拟",
    attentionStatus: "持续观察",
    updatedAt: "2026-08-06T09:00:00.000Z",
    positions: [
      {
        nodeId: "components",
        positionType: "primary",
        status: "confirmed",
        confidence: 1,
        source: "manual",
        sourceDate: "2026-08-06",
      },
    ],
    evidence: [
      {
        id: "e-ae1",
        documentId: "d-ae1",
        fileName: "Demo模拟资料_星载元器件供应商访谈纪要.docx",
        excerpt:
          "【Demo 模拟】该公司面向低轨通信卫星平台提供星载计算模块、射频前端和电源组件，样品已进入联合验证阶段。",
        page: 2,
        sourceDate: "2026-07-12",
        visibility: "organization",
      },
      {
        id: "e-ae2",
        documentId: "d-ae2",
        fileName: "Demo模拟资料_关键元器件国产化研究.pdf",
        excerpt:
          "【Demo 模拟】卫星批量制造将增加对高可靠、低成本星载元器件的采购需求。",
        page: 11,
        sourceDate: "2026-06-20",
        visibility: "organization",
      },
    ],
    claims: [
      {
        id: "cl-ae1",
        category: "产业关系",
        text: "【Demo 模拟】作为卫星平台上游元器件供应商，与银河航天存在潜在供应链关联。",
        type: "ai_inference",
        status: "candidate",
        confidence: 0.79,
        version: 1,
        evidenceIds: ["e-ae1", "e-ae2"],
        visibility: "organization",
      },
    ],
  },
  {
    id: "c-space-material",
    standardName: "空天复合材料示范公司",
    aliases: ["空天材料示范"],
    description: "Demo 模拟企业：提供卫星结构用复合材料和热控材料。",
    cognitionStatus: "Demo 模拟",
    attentionStatus: "机构未关注",
    updatedAt: "2026-08-06T09:00:00.000Z",
    positions: [
      {
        nodeId: "materials",
        positionType: "primary",
        status: "confirmed",
        confidence: 1,
        source: "manual",
        sourceDate: "2026-08-06",
      },
    ],
    evidence: [
      {
        id: "e-sm1",
        documentId: "d-sm1",
        fileName: "Demo模拟资料_卫星轻量化材料BP.pdf",
        excerpt:
          "【Demo 模拟】产品用于卫星承力结构、天线支撑和热控系统，可降低整星结构质量。",
        page: 6,
        sourceDate: "2026-07-04",
        visibility: "organization",
      },
    ],
    claims: [
      {
        id: "cl-sm1",
        category: "产业关系",
        text: "【Demo 模拟】位于卫星平台上游基础材料环节。",
        type: "verified_fact",
        status: "confirmed",
        confidence: 0.9,
        version: 1,
        evidenceIds: ["e-sm1"],
        visibility: "organization",
      },
    ],
  },
  {
    id: "c-ground-network",
    standardName: "星地测运控示范公司",
    aliases: ["星地测控示范"],
    description: "Demo 模拟企业：提供商业卫星地面站、测控排班和在轨运维服务。",
    cognitionStatus: "Demo 模拟",
    attentionStatus: "个人关注",
    updatedAt: "2026-08-06T09:00:00.000Z",
    positions: [
      {
        nodeId: "ground-station",
        positionType: "primary",
        status: "confirmed",
        confidence: 1,
        source: "manual",
        sourceDate: "2026-08-06",
      },
    ],
    evidence: [
      {
        id: "e-gn1",
        documentId: "d-gn1",
        fileName: "Demo模拟资料_商业卫星测运控项目纪要.docx",
        excerpt:
          "【Demo 模拟】已完成与三型低轨通信卫星的测控接口适配，可提供常态化在轨运维。",
        page: 4,
        sourceDate: "2026-07-21",
        visibility: "organization",
      },
    ],
    claims: [
      {
        id: "cl-gn1",
        category: "产业关系",
        text: "【Demo 模拟】位于卫星平台下游地面站与测运控环节。",
        type: "verified_fact",
        status: "confirmed",
        confidence: 0.93,
        version: 1,
        evidenceIds: ["e-gn1"],
        visibility: "organization",
      },
    ],
  },
  {
    id: "c-sat-service",
    standardName: "低轨网络运营示范公司",
    aliases: ["低轨运营示范"],
    description:
      "Demo 模拟企业：面向应急通信和行业客户提供卫星互联网运营服务。",
    cognitionStatus: "Demo 模拟",
    attentionStatus: "推荐团队",
    updatedAt: "2026-08-06T09:00:00.000Z",
    positions: [
      {
        nodeId: "sat-internet",
        positionType: "primary",
        status: "confirmed",
        confidence: 1,
        source: "manual",
        sourceDate: "2026-08-06",
      },
    ],
    evidence: [
      {
        id: "e-so1",
        documentId: "d-so1",
        fileName: "Demo模拟资料_低轨卫星互联网应用研究.pdf",
        excerpt:
          "【Demo 模拟】低轨网络运营服务需要卫星平台、地面站和用户终端共同支撑。",
        page: 8,
        sourceDate: "2026-07-16",
        visibility: "organization",
      },
      {
        id: "e-so2",
        documentId: "d-so2",
        fileName: "Demo模拟资料_行业客户需求访谈.docx",
        excerpt:
          "【Demo 模拟】应急管理客户关注终端便携性、网络可用性和按需计费能力。",
        page: 3,
        sourceDate: "2026-07-29",
        visibility: "organization",
      },
    ],
    claims: [
      {
        id: "cl-so1",
        category: "产业关系",
        text: "【Demo 模拟】位于银河航天下游卫星互联网运营服务环节。",
        type: "ai_inference",
        status: "candidate",
        confidence: 0.84,
        version: 1,
        evidenceIds: ["e-so1", "e-so2"],
        visibility: "organization",
      },
    ],
  },
];

const additionalCompanySpecs = [
  [
    "c-orbit-payload",
    "寰宇载荷科技示范公司",
    "寰宇载荷",
    "sat-payload",
    "卫星有效载荷",
  ],
  [
    "c-terminal-one",
    "天链终端设备示范公司",
    "天链终端",
    "terminal",
    "卫星通信终端",
  ],
  [
    "c-terminal-two",
    "星通便携终端示范公司",
    "星通终端",
    "terminal",
    "便携式卫星终端",
  ],
  [
    "c-remote-one",
    "云图遥感示范公司",
    "云图遥感",
    "remote-sensing",
    "遥感数据服务",
  ],
  ["c-nav-one", "北斗应用示范公司", "北斗应用", "navigation", "卫星导航应用"],
  ["c-comms-one", "星网通信示范公司", "星网通信", "sat-comms", "卫星通信服务"],
  [
    "c-engine-one",
    "深空动力示范公司",
    "深空动力",
    "rocket-engine",
    "液体火箭发动机",
  ],
  [
    "c-structure-one",
    "箭体结构示范公司",
    "箭体结构",
    "rocket-structure",
    "运载火箭结构系统",
  ],
  [
    "c-platform-two",
    "星舟卫星平台示范公司",
    "星舟卫星",
    "sat-platform",
    "小卫星平台",
  ],
  [
    "c-platform-three",
    "星舟科技（上海）有限公司",
    "星舟科技",
    "sat-platform",
    "卫星平台研制",
  ],
  [
    "c-platform-four",
    "星舟科技（深圳）有限公司",
    "星舟科技",
    "components",
    "星载元器件",
  ],
  [
    "c-galactic-energy",
    "北京星河动力装备科技有限公司",
    "星河动力",
    "rocket-engine",
    "商业运载火箭",
  ],
  [
    "c-galaxy-history",
    "银河航天科技历史主体示范公司",
    "银河科技",
    "sat-platform",
    "历史名称消歧样例",
  ],
] as const;

for (const [
  id,
  standardName,
  alias,
  nodeId,
  product,
] of additionalCompanySpecs) {
  const evidence = Array.from({ length: 4 }, (_, index) => ({
    id: `e-${id.slice(2)}-${index + 1}`,
    documentId: `d-${id.slice(2)}-${index + 1}`,
    fileName: `Demo模拟资料_${alias}_${["BP", "访谈纪要", "内部研究", "外部动态"][index]}.${index === 0 || index === 2 ? "pdf" : index === 1 ? "docx" : "md"}`,
    excerpt: `【Demo 模拟】${standardName}围绕${product}开展业务。本条为第 ${index + 1} 份验收资料，用于验证检索、证据与权限链路。`,
    page: index + 2,
    sourceDate: `2026-0${Math.min(8, index + 4)}-${String(index + 10).padStart(2, "0")}`,
    visibility: "organization" as const,
  }));
  companies.push({
    id,
    standardName,
    aliases: [alias],
    description: `Demo 模拟企业：聚焦${product}。`,
    cognitionStatus: "Demo 模拟",
    attentionStatus: "机构未关注",
    updatedAt: "2026-08-06T09:00:00.000Z",
    positions: [
      {
        nodeId,
        positionType: "primary",
        status: id === "c-platform-four" ? "candidate" : "confirmed",
        confidence: 0.88,
        source: id === "c-platform-four" ? "source_map" : "manual",
        sourceDate: id === "c-platform-four" ? "2025-12-03" : "2026-08-06",
      },
    ],
    evidence,
    claims: Array.from({ length: 4 }, (_, index) => ({
      id: `cl-${id.slice(2)}-${index + 1}`,
      category: ["主营产品", "技术能力", "客户场景", "产业位置"][index],
      text: `【Demo 模拟】${standardName}${["主营", "具备", "服务于", "位于产业链"][index]}${product}${index === 3 ? "相关环节" : ""}。`,
      type:
        index === 0
          ? ("company_statement" as const)
          : index === 3
            ? ("ai_inference" as const)
            : ("verified_fact" as const),
      status: index === 3 ? ("candidate" as const) : ("confirmed" as const),
      confidence: 0.82 + index * 0.03,
      version: 1,
      evidenceIds: [evidence[index].id],
      visibility: "organization" as const,
    })),
  });
}

// 五家核心公司各准备十条可核验证据陈述，满足 Demo 标准答案集规模。
for (const company of companies.slice(0, 5)) {
  while (company.claims.length < 10) {
    const index = company.claims.length + 1;
    const evidenceId = `e-${company.id.slice(2)}-core-${index}`;
    company.evidence.push({
      id: evidenceId,
      documentId: `d-${company.id.slice(2)}-core-${index}`,
      fileName: `Demo模拟资料_${company.aliases[0]}_核心事实${index}.md`,
      excerpt: `【Demo 模拟】${company.standardName}核心事实 ${index} 的标准答案与引用片段。`,
      sourceDate: "2026-08-01",
      visibility: "organization",
    });
    company.claims.push({
      id: `cl-${company.id.slice(2)}-core-${index}`,
      category: `核心事实 ${index}`,
      text: `【Demo 模拟】${company.standardName}核心事实 ${index}。`,
      type: index % 4 === 0 ? "ai_inference" : "verified_fact",
      status: index % 4 === 0 ? "candidate" : "confirmed",
      confidence: 0.86,
      version: 1,
      evidenceIds: [evidenceId],
      visibility: "organization",
    });
  }
}

export const tasks: ResearchTask[] = [
  {
    id: "t-demo",
    query: "帮我了解银河航天，并核验它在商业航天产业链中的位置",
    companyId: "c-galaxy",
    status: "待用户确认",
    createdBy: "u-investor",
    createdAt: "2026-08-06T08:00:00.000Z",
    steps: [
      {
        name: "识别公司主体",
        status: "done",
        detail: "已匹配银河航天（北京）科技有限公司",
      },
      {
        name: "检索内部历史",
        status: "done",
        detail: "找到 3 份当前用户可见资料",
      },
      {
        name: "匹配产业链",
        status: "needs-review",
        detail: "1 个已确认位置，1 个图谱候选位置",
      },
      {
        name: "核验证据与冲突",
        status: "done",
        detail: "发现 1 条待核验企业表述",
      },
      { name: "生成公司认知包", status: "done", detail: "已生成 4 类知识陈述" },
    ],
  },
];

export const audits: AuditEvent[] = [
  {
    id: "a1",
    actor: "知识管理员",
    action: "导入知识源",
    target: "商业航天图谱",
    at: "2026-08-06T07:10:00.000Z",
    detail: "导入五大一级板块及候选企业映射",
  },
  {
    id: "a2",
    actor: "陈晨",
    action: "发起研究",
    target: "银河航天",
    at: "2026-08-06T08:00:00.000Z",
    detail: "公司研究任务 t-demo",
  },
  {
    id: "a3",
    actor: "系统",
    action: "权限过滤",
    target: "研究任务 t-demo",
    at: "2026-08-06T08:01:00.000Z",
    detail: "过滤 0 条无权限候选",
  },
];
