import type { FundMatchSource, FundProfile } from './contracts.js';

export const MOCK_CHENGDU_FUND_SOURCE: FundMatchSource = {
  fileName: '模拟私募基金清单_4只_成都.xlsx',
  asOfDate: '2026-08-28',
  simulated: true,
};

export const MOCK_CHENGDU_FUNDS: FundProfile[] = [
  {
    fundId: 'F01',
    fundName: '成都锦江远见硬科技创业投资合伙企业（有限合伙）',
    fundType: '创业投资基金',
    establishedOn: '2018-07-11',
    investmentPeriodEnd: '2023-07-10',
    maturityOn: '2028-07-10',
    committedAmountWan: 260_000,
    paidInAmountWan: 260_000,
    investedAmountWan: 256_500,
    availableAmountWan: 3_500,
    totalAssetsWan: 612_700,
    netAssetsWan: 605_400,
    investorCount: 24,
    investmentPeriodActive: false,
    capitalAvailable: false,
    ticketMinWan: 5_000,
    concentrationLimit: 0.1,
    ticketMaxWan: 26_000,
    industryPreferences: ['AI推理基础设施', '机器人传感/Physical AI', '商业航天高可靠电子', '量子科技'],
    stagePreferences: ['Pre-A轮', 'A轮', 'B轮'],
    regionPreference: '全国（成渝、长三角、大湾区）',
    source: MOCK_CHENGDU_FUND_SOURCE,
  },
  {
    fundId: 'F02',
    fundName: '四川天府精硅股权投资合伙企业（有限合伙）',
    fundType: '私募股权投资基金',
    establishedOn: '2021-09-08',
    investmentPeriodEnd: '2026-09-07',
    maturityOn: '2031-09-07',
    committedAmountWan: 350_000,
    paidInAmountWan: 325_500,
    investedAmountWan: 268_000,
    availableAmountWan: 57_500,
    totalAssetsWan: 589_300,
    netAssetsWan: 582_100,
    investorCount: 12,
    investmentPeriodActive: true,
    capitalAvailable: true,
    ticketMinWan: 2_000,
    concentrationLimit: 0.12,
    ticketMaxWan: 42_000,
    industryPreferences: ['半导体设备核心零部件', 'HBM/先进封装', 'CPO/光互连/高速网络', '新型显示与光电子'],
    stagePreferences: ['A轮', 'B轮'],
    regionPreference: '全国（长三角、成渝为重点）',
    source: MOCK_CHENGDU_FUND_SOURCE,
  },
  {
    fundId: 'F03',
    fundName: '成都元屿智算创业投资合伙企业（有限合伙）',
    fundType: '创业投资基金',
    establishedOn: '2023-03-21',
    investmentPeriodEnd: '2027-03-20',
    maturityOn: '2032-03-20',
    committedAmountWan: 120_000,
    paidInAmountWan: 96_000,
    investedAmountWan: 51_000,
    availableAmountWan: 45_000,
    totalAssetsWan: 131_200,
    netAssetsWan: 128_600,
    investorCount: 15,
    investmentPeriodActive: true,
    capitalAvailable: true,
    ticketMinWan: 500,
    concentrationLimit: 0.15,
    ticketMaxWan: 18_000,
    industryPreferences: ['AI Infra', 'AI推理基础设施', 'CPO/光互连/高速网络'],
    stagePreferences: ['天使轮', 'Pre-A轮', 'A轮'],
    regionPreference: '全国',
    source: MOCK_CHENGDU_FUND_SOURCE,
  },
  {
    fundId: 'F04',
    fundName: '成都启物机器人创业投资合伙企业（有限合伙）',
    fundType: '创业投资基金',
    establishedOn: '2024-02-27',
    investmentPeriodEnd: '2028-02-26',
    maturityOn: '2034-02-26',
    committedAmountWan: 100_000,
    paidInAmountWan: 65_000,
    investedAmountWan: 28_000,
    availableAmountWan: 37_000,
    totalAssetsWan: 68_900,
    netAssetsWan: 67_400,
    investorCount: 13,
    investmentPeriodActive: true,
    capitalAvailable: true,
    ticketMinWan: 300,
    concentrationLimit: 0.2,
    ticketMaxWan: 20_000,
    industryPreferences: ['机器人传感/Physical AI', 'AI推理基础设施'],
    stagePreferences: ['天使轮', 'Pre-A轮'],
    regionPreference: '成渝为主、面向全国',
    source: MOCK_CHENGDU_FUND_SOURCE,
  },
];
